from gestaoapp.models.dia import Dia
from gestaoapp.models.horario import Horario 
from gestaoapp.models.usuario import Usuario
from gestaoapp.models.turno	import Turno
from gestaoapp.models.vinculo import Vinculo
from gestaoapp.models.nucleo import Nucleo
from gestaoapp.models.recurso import Recurso
from gestaoapp.models.tiporecurso import TipoRecurso
from gestaoapp.models.artefato import Artefato
from gestaoapp.models.atividade import Atividade
from gestaoapp.models.edital import Edital
from gestaoapp.models.tipoprojeto import TipoProjeto
from gestaoapp.models.projeto import Projeto
from gestaoapp.models.situacaoprojeto import SituacaoProjeto
from gestaoapp.models.faseprojeto import FaseProjeto
from gestaoapp.models.horaprojeto import HoraProjeto
